declare module 'bootstrap-vue/esm/components/dropdown/dropdown-item'
declare module 'bootstrap-vue/esm/components/modal/modal'
declare module 'bootstrap-vue/esm/components/nav/nav-item-dropdown'
declare module 'bootstrap-vue/esm/components/popover/popover'
declare module 'bootstrap-vue/esm/components/tooltip/tooltip'